title: L4zyG33k Stuff
description: Stay Hungry. Stay Foolish.
theme: jekyll-theme-cayman
show_downloads: false
navigation: True
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
plugins:
- jekyll-feed
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-avatar
- jemoji
- jekyll-mentions
- jekyll-include-cache
